# Generated by Django 6.0.4 on 2026-04-17 03:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ajogo", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="admin",
            options={"verbose_name": "admin", "verbose_name_plural": "admins"},
        ),
        migrations.AlterModelOptions(
            name="contribution",
            options={"verbose_name": " contribution"},
        ),
        migrations.AlterModelOptions(
            name="group",
            options={"verbose_name": "group", "verbose_name_plural": "groups"},
        ),
    ]
