# Generated by Django 6.0.4 on 2026-04-17 03:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ajogo", "0004_alter_admin_options_alter_group_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="member",
            options={"ordering": ["rotation_order"], "verbose_name": " Member"},
        ),
    ]
