# Generated by Django 6.0.3 on 2026-04-17 13:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ajogo", "0006_savingsgroup_remove_group_admin_customuser_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CustomUser",
        ),
    ]
