# Generated by Django 6.0.4 on 2026-04-17 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ajogo", "0003_alter_contribution_options_alter_group_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="admin",
            options={"verbose_name": " Admin", "verbose_name_plural": " Admins"},
        ),
        migrations.AlterModelOptions(
            name="group",
            options={"verbose_name": " Group", "verbose_name_plural": " Groups"},
        ),
    ]
