# Generated by Django 6.0.4 on 2026-04-17 04:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ajogo", "0005_alter_member_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sender", models.CharField(max_length=100)),
                ("content", models.TextField()),
                (
                    "post_type",
                    models.CharField(
                        choices=[
                            ("post", "Post"),
                            ("message", "Message"),
                            ("comment", "Comment"),
                        ],
                        default="message",
                        max_length=10,
                    ),
                ),
                ("timestamp", models.DateTimeField()),
                ("raw_members", models.JSONField(default=list)),
                ("raw_line", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to="ajogo.group",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="ajogo.post",
                    ),
                ),
            ],
            options={
                "db_table": "posts",
                "ordering": ["-timestamp"],
            },
        ),
    ]
