# Generated by Django 6.0.4 on 2026-04-17 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ajogo", "0007_alter_contribution_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contribution",
            options={
                "verbose_name": "Contribution",
                "verbose_name_plural": "Contributions",
            },
        ),
    ]
