# Generated by Django 6.0.4 on 2026-04-17 03:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ajogo", "0002_alter_admin_options_alter_contribution_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contribution",
            options={"verbose_name": "contribution"},
        ),
        migrations.AlterModelOptions(
            name="group",
            options={"verbose_name": " group", "verbose_name_plural": " groups"},
        ),
    ]
