# Generated by Django 6.0.4 on 2026-04-17 16:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("apps", "0002_savingsgroup_groupmembers"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="GroupMembers",
            new_name="GroupMember",
        ),
        migrations.AlterModelOptions(
            name="savingsgroup",
            options={
                "verbose_name": "  Savings Group",
                "verbose_name_plural": "  Savings Groups",
            },
        ),
    ]
