# Generated by Django 6.0.4 on 2026-04-17 17:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apps", "0004_contribution_payout_reminderrule_reminderstate"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contribution",
            options={"verbose_name": " Contribution"},
        ),
        migrations.AlterModelOptions(
            name="groupmember",
            options={"ordering": ["rotation_order"], "verbose_name": "  Member"},
        ),
        migrations.AlterModelOptions(
            name="reminderrule",
            options={"verbose_name": " Reminder Rule"},
        ),
        migrations.AlterModelOptions(
            name="reminderstate",
            options={"verbose_name": " Reminder State"},
        ),
        migrations.AlterModelOptions(
            name="savingsgroup",
            options={"verbose_name": "   Savings Group"},
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sender", models.CharField(max_length=100)),
                ("content", models.TextField()),
                (
                    "post_type",
                    models.CharField(
                        choices=[
                            ("post", "Post"),
                            ("message", "Message"),
                            ("comment", "Comment"),
                        ],
                        default="message",
                        max_length=10,
                    ),
                ),
                ("timestamp", models.DateTimeField()),
                ("raw_members", models.JSONField(default=list)),
                ("raw_line", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to="apps.savingsgroup",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="apps.post",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "posts",
                "ordering": ["-timestamp"],
            },
        ),
    ]
